// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingOrder = `-- name: CancelPendingOrder :one
UPDATE orders
SET status = 'CANCELLED',
    updated_at = now()
WHERE id = $1
  AND customer_id = $2
  AND status = 'PENDING'
RETURNING id, customer_id, status, idempotency_key, total_cents, currency, created_at, updated_at
`

type CancelPendingOrderParams struct {
	ID         pgtype.UUID
	CustomerID pgtype.UUID
}

func (q *Queries) CancelPendingOrder(ctx context.Context, arg CancelPendingOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, cancelPendingOrder, arg.ID, arg.CustomerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    customer_id,
    status,
    idempotency_key,
    total_cents,
    currency
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, customer_id, status, idempotency_key, total_cents, currency, created_at, updated_at
`

type CreateOrderParams struct {
	ID             pgtype.UUID
	CustomerID     pgtype.UUID
	Status         string
	IdempotencyKey string
	TotalCents     int64
	Currency       string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.CustomerID,
		arg.Status,
		arg.IdempotencyKey,
		arg.TotalCents,
		arg.Currency,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderEvent = `-- name: CreateOrderEvent :one
INSERT INTO order_events (
    id,
    order_id,
    actor_type,
    actor_id,
    from_status,
    to_status,
    action,
    reason,
    ip_address
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, order_id, actor_type, actor_id, from_status, to_status, action, reason, ip_address, created_at
`

type CreateOrderEventParams struct {
	ID         pgtype.UUID
	OrderID    pgtype.UUID
	ActorType  string
	ActorID    pgtype.UUID
	FromStatus pgtype.Text
	ToStatus   pgtype.Text
	Action     string
	Reason     pgtype.Text
	IpAddress  *netip.Addr
}

func (q *Queries) CreateOrderEvent(ctx context.Context, arg CreateOrderEventParams) (OrderEvent, error) {
	row := q.db.QueryRow(ctx, createOrderEvent,
		arg.ID,
		arg.OrderID,
		arg.ActorType,
		arg.ActorID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Action,
		arg.Reason,
		arg.IpAddress,
	)
	var i OrderEvent
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ActorType,
		&i.ActorID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Action,
		&i.Reason,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    id,
    order_id,
    product_id,
    sku,
    quantity,
    unit_price_cents
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, order_id, product_id, sku, quantity, unit_price_cents, created_at
`

type CreateOrderItemParams struct {
	ID             pgtype.UUID
	OrderID        pgtype.UUID
	ProductID      pgtype.UUID
	Sku            string
	Quantity       int32
	UnitPriceCents int64
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.Sku,
		arg.Quantity,
		arg.UnitPriceCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Sku,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByIDAndCustomerID = `-- name: GetOrderByIDAndCustomerID :one
SELECT id, customer_id, status, idempotency_key, total_cents, currency, created_at, updated_at
FROM orders
WHERE id = $1
  AND customer_id = $2
LIMIT 1
`

type GetOrderByIDAndCustomerIDParams struct {
	ID         pgtype.UUID
	CustomerID pgtype.UUID
}

func (q *Queries) GetOrderByIDAndCustomerID(ctx context.Context, arg GetOrderByIDAndCustomerIDParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIDAndCustomerID, arg.ID, arg.CustomerID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderEventsByOrderID = `-- name: GetOrderEventsByOrderID :many
SELECT id, order_id, actor_type, actor_id, from_status, to_status, action, reason, ip_address, created_at
FROM order_events
WHERE order_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) GetOrderEventsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderEvent, error) {
	rows, err := q.db.Query(ctx, getOrderEventsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderEvent
	for rows.Next() {
		var i OrderEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ActorType,
			&i.ActorID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Action,
			&i.Reason,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, order_id, product_id, sku, quantity, unit_price_cents, created_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Sku,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomerID = `-- name: ListOrdersByCustomerID :many
SELECT id, customer_id, status, idempotency_key, total_cents, currency, created_at, updated_at
FROM orders
WHERE customer_id = $1
  AND (
    $3::timestamptz IS NULL
    OR (
      created_at < $3::timestamptz
      OR (
        created_at = $3::timestamptz
        AND id < $4::uuid
      )
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListOrdersByCustomerIDParams struct {
	CustomerID      pgtype.UUID
	Limit           int32
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListOrdersByCustomerID(ctx context.Context, arg ListOrdersByCustomerIDParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomerID,
		arg.CustomerID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Status,
			&i.IdempotencyKey,
			&i.TotalCents,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomerIDAndStatus = `-- name: ListOrdersByCustomerIDAndStatus :many
SELECT id, customer_id, status, idempotency_key, total_cents, currency, created_at, updated_at
FROM orders
WHERE customer_id = $1
  AND status = $2
  AND (
    $4::timestamptz IS NULL
    OR (
      created_at < $4::timestamptz
      OR (
        created_at = $4::timestamptz
        AND id < $5::uuid
      )
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListOrdersByCustomerIDAndStatusParams struct {
	CustomerID      pgtype.UUID
	Status          string
	Limit           int32
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
}

func (q *Queries) ListOrdersByCustomerIDAndStatus(ctx context.Context, arg ListOrdersByCustomerIDAndStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomerIDAndStatus,
		arg.CustomerID,
		arg.Status,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Status,
			&i.IdempotencyKey,
			&i.TotalCents,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatusIfCurrentStatusMatches = `-- name: UpdateOrderStatusIfCurrentStatusMatches :one
UPDATE orders
SET status = $3,
    updated_at = now()
WHERE id = $1
  AND status = $2
RETURNING id, customer_id, status, idempotency_key, total_cents, currency, created_at, updated_at
`

type UpdateOrderStatusIfCurrentStatusMatchesParams struct {
	ID       pgtype.UUID
	Status   string
	Status_2 string
}

func (q *Queries) UpdateOrderStatusIfCurrentStatusMatches(ctx context.Context, arg UpdateOrderStatusIfCurrentStatusMatchesParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatusIfCurrentStatusMatches, arg.ID, arg.Status, arg.Status_2)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalCents,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const workerPickAndMovePendingOrdersToProcessing = `-- name: WorkerPickAndMovePendingOrdersToProcessing :many
WITH picked_orders AS (
    SELECT id
    FROM orders
    WHERE status = 'PENDING'
    ORDER BY created_at ASC, id ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE orders
SET status = 'PROCESSING',
    updated_at = now()
WHERE id IN (
    SELECT id
    FROM picked_orders
)
RETURNING id, customer_id, status, idempotency_key, total_cents, currency, created_at, updated_at
`

func (q *Queries) WorkerPickAndMovePendingOrdersToProcessing(ctx context.Context, limit int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, workerPickAndMovePendingOrdersToProcessing, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Status,
			&i.IdempotencyKey,
			&i.TotalCents,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
